export const adjectives = [
  'Boiling',
  'Fluffy',
  'Sharp',
  'Breezy',
  'Freezing',
  'Silky',
  'Bumpy',
  'Fuzzy',
  'Slick',
  'Chilly',
  'Greasy',
  'Slimy',
  'Cold',
  'Hard',
  'Slippery',
  'Cool',
  'Hot',
  'Smooth',
  'Cuddly',
  'Icy',
  'Soft',
  'Damp',
  'Loose',
  'Solid',
  'Dirty',
  'Melted',
  'Sticky',
  'Dry',
  'Painful',
  'Tender',
  'Dusty',
  'Prickly',
  'Tight',
  'Encrusted',
  'Rough',
  'Uneven',
  'Filthy',
  'Shaggy',
  'Warm',
  'Flaky',
  'Shaky',
  'Wet',
];

export const roomNouns = [
  'Bay',
  'Pass',
  'Room',
  'House',
  'Inn',
  'Village',
  'Town',
  'Beach',
  'Desert',
  'River',
  'Creek',
  'Cavern',
  'Peninsula',
  'Haven',
  'Valley',
  'Sea',
  'Sanctuary',
];

export const usernameNouns = [
  'Benevolent Cinderboop',
  'Banjoflip Cummerbooger',
  'Beefbloke Childthatch',
  'Broccoli Cinderwhaler',
  'Battlefield Counterstrike',
  'Bassgarble Crackercrumb',
  'Billywhisker Cabbagepatch',
  'Bastard',
  'Crook',
  'Scoundrel',
  'Doopzko',
];

export function getRandomInt(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min)) + min; //The maximum is exclusive and the minimum is inclusive
}
